### ISSUE TITLE
Some assistance in getting your elk-cluster up-and-running

### ISSUE THREAD

**Issue by Analect** [Mirantis/k8s-apps#3]
First up, thanks for these resources.
I wanted to run up an elk-cluster.  I modified the elasticsearch and logstash images to include extra plugins I needed and rebuilt those images manually and pushed them to my own registry and then referenced those images accordingly under `values.yaml` under both respective charts folders.  I also updated elasticsearch host in the `values.yaml` in both kibana and logstash charts to point to `elasticsearch-elasticsearch` ... as it was my intention to install the cluster with `helm install --name elasticsearch .` ... which would drive the naming of the second element in the elasticsearch service.

With those changes in place, I ran `helm dep build` under the `charts/elk-cluster` folder.  I think this is a necessary step, is it?  And I think this broadly worked, although I'm not sure about the `connection refused` part.

```
helm dep build
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: getsockopt: connection refused
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 3 charts
```
However, when I then try to install the cluster, I get this.  It's not clear to me where the missing `ls-es-url` parameter gets set.  Ideally, I'm wanting elasticsearch and logstash to be internal to the cluster, but be able to access kibana externally.  Any pointers on where I might be going wrong would be much appreciated.  Thanks.

```
mccoole@ubuntu-1404:~/Development/Tools/Eolas/infrastructure/mirantis-k8s-apps/charts/elk-cluster$ helm install --name elasticsearch .
Error: render error in "elk-cluster/templates/tests/full-elk-test.yaml": template: elk-cluster/templates/tests/full-elk-test.yaml:2:14: executing "elk-cluster/templates/tests/full-elk-test.yaml" at <include "ls-es-url" ...>: error calling include: template: no template "ls-es-url" associated with template "gotpl"
```

**Comment by Analect** [comment]
Just as a follow-on question, I can see that there's no default persistent for ElasticSearch.

I was trying to figure out what is expected in `storageClass` in values.yaml if I set type to `PersistentVolumeClaim`.  Do I need to manually create a persistent volume myself on GKE? ... thanks.

```
data:
  replicas: 1
  heapSize: 1536m
  resources:
    requests:
      cpu: 256m
      memory: 2Gi
    #limits:
    #  cpu: 1
    #  memory: 4Gi
  persistence:
    type: PersistentVolumeClaim # or hostPath or PersistentVolumeClaim
    storageClass: "gce-standard-storage"
    volumeSize: 20Gi
    hostPath: ""
```

**Comment by prazumovsky** [comment]
Hello, @Analect !

First of all, which version of helm/k8s you used?

> I'm not sure about the connection refused part

Probably you have no "local" repo, so it cannot be found:)

> I ran helm dep build under the charts/elk-cluster folder.

Did you run elk-cluster earlier, before logstash/esc changing? I'd recommend to use `helm dep up` instead, it will update `charts/` folder under `elk-cluster/`.

And also could you share `values.yaml` of elk-cluster? Or it's default?

**Comment by Analect** [comment]
@prazumovsky 
I'm using helm version 2.5.0 (both client and server).  The server side being a GKE cluster.
Not sure about the 'local' repo part ... I clone this repo my machine and was hoping to run helm directly from the clone.
I haven't changed the elk-cluster values.yaml.  I have only changed the values.yaml in logstash and elasticsearch to point to my own image versions (with additional plugins).  Also, in the ES yaml, I have change the storage to pvc, as per below.  Otherwise, I haven't altered anything else.

amended elasticsearch (component of elk-cluster) values.yaml:
```
# Default values for elasticsearch.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

port: 9200
transportPort: 9300

probeInitialDelaySeconds: 90
probeTimeoutSeconds: 5

image:
  repository: myimage_registry/mirantis/
  name: elasticsearch
  tag: 5.2.2
  pullPolicy: Always

master:
  replicas: 1
  heapSize: 1G
  resources:
    requests:
      cpu: 256m
      memory: 512Mi
    #limits:
    #  cpu: 512m
    #  memory: 1Gi

client:
  replicas: 1
  heapSize: 1G
  resources:
    requests:
      cpu: 256m
      memory: 512Mi
    #limits:
    #  cpu: 512m
    #  memory: 1Gi
  service:
    type: ClusterIP # or NodePort or LoadBalancer
    nodePort: ""
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    annotations: {}
  ingress:
    enabled: false
    hosts: []
    #  - some.domain
    tls:
      enabled: false
      secretName: ""
    annotations: {}
    #  kubernetes.io/ingress.class: nginx

data:
  replicas: 1
  heapSize: 1536m
  resources:
    requests:
      cpu: 256m
      memory: 2Gi
    #limits:
    #  cpu: 1
    #  memory: 4Gi
  persistence:
    type: PersistentVolumeClaim # or hostPath or PersistentVolumeClaim
    storageClass: "gce-standard-storage"
    volumeSize: 20Gi
    hostPath: ""
```

I have run `helm dep up`, as you recommend, but somehow it's expecting this repo to be served over port 8879?  Am I missing something?

```
/mirantis-k8s-apps/charts/elk-cluster$ helm dep up
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: getsockopt: connection refused
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 3 charts
```
